swagger: '2.0'

info:
  version: "0.0.1"
  title: Iddeal Trello Burndown
basePath: /api/
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:

  /hello:
    x-swagger-router-controller: helloController
    get:
      description: Returns 'Hello' to the caller
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /CardHistory:
    x-swagger-router-controller: cardHistoryController
    post:
      description: |
        Snapshots the current list state of the cards
      parameters:
        - in: body
          name: updates
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/WriteCardHistory"
      responses:
        204:
          description: Success
    get:
      description: |
        Gets a list of history of the cards
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/ReadCardHistory"

  /CardHistory/Orphans:
    x-swagger-router-controller: cardHistoryController
    get:
      operationId: orphans
      description: |
        Gets a list of the Card Numbers or List Ids we have history for but not the actual item
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/ReadCardHistoryOrphan"
        
  /Lists/{listId}:
    put:
      description: |
        Create or replace the List with the given Id
      parameters:
        - in: path 
          name: listId
          required: true
          type: integer
          format: int32
        - in: body 
          name: list
          required: true
          schema:
            $ref: "#/definitions/WriteList"
      responses:
        201:
          description: Successfully created List
        204:
          description: Successfully replaced existing List
    get:
      description: |
        Gets the List with the given Id
      parameters:
        - in: path 
          name: listId
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ReadList"
        404:
          description: Not Found
          
  /Lists/:
    get:
      description: |
        Gets all Lists
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/ReadList"
              
  /Cards/{cardNumber}:
    get:
      description: |
        Gets the Cist with the given Number
      parameters:
        - in: path 
          name: cardNumber
          required: true
          type: integer
          format: int32
      responses:
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/ReadCard"
        404:
          description: Not Found
    put:
      description: |
        Create or replace the Card with the given Number
      parameters:
        - in: path 
          name: cardNumber
          required: true
          type: integer
          format: int32
        - in: body
          name: card
          required: true
          schema:
            $ref: "#/definitions/WriteCard"
      responses:
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/ReadCard"
            
  /Cards/:
    get:
      description: |
        Gets all Cards
      responses:
        200: 
          description: Success
          schema: 
            type: array
            items:
              $ref: "#/definitions/ReadCard"
              
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Status:
    type: string
    enum:
      - backlog
      - dev
      - qa
      - done
  WriteCardHistory:
    type: object
    properties:
      cardNo:
        type: integer
        format: int32
      listId: 
        type: integer
        format: int32
  ReadCardHistory:
    type: object
    properties:
      status:
        $ref: "#/definitions/Status"
      createdAt:
        type: string
        format: date
  ReadCardHistoryOrphan:
    type: object
    description: Only one of cardNo or listId will be set
    properties:
      cardNo:
        type: integer
        format: int32
      listId:
        type: integer
        format: int32
  WriteList:
    type: object
    properties:
      name:
        type: string
      status:
        $ref: "#/definitions/Status"
      displayPosition:
        type: integer
        format: int32
        description: The display position of this list
  ReadList:
    type: object
    allOf: 
      - $ref: "#/definitions/WriteList"
      - properties:
          listId:
            type: integer
            format: int32
  WriteCard:
    type: object
    properties:
      title:
        type: string
      uri:
        type: string
        format: uri
  ReadCard:
    type: object
    allOf:
      - $ref: "#/definitions/WriteCard"
      - properties:
          CardNumber:
            type: integer
            format: int32
